import {expect} from 'chai';
import pdftojson from '../../src';

describe('pdftojson', () => {
  it('should parse pdf', () => {
    return pdftojson('test/fixture/twolines.pdf').then(pages => {
      expect(pages.length).to.equal(1);
      expect(pages[0].words.map(w => w.text)).to.deep.equal([
        '中文 English にほんご',
        'All\t\r \xa0in\t\r \xa01\t\r \xa0line!'
        // PDF generated by MS Word is dirty......
      ]);
    });
  });
});
